project: default
source:
  repoURL: 'https://github.com/yurll/gitops-cert-level-2-examples/'
  path: ./environment-promotion/envs/staging
destination:
  server: 'https://kubernetes.default.svc'
  namespace: staging
syncPolicy:
  automated:
    prune: true
    selfHeal: true
